### ISSUE TITLE
Collisions out of place when first tile is solid

### ISSUE THREAD

**Issue by unbelievableflavour** [NicMagnier/PlaydateLDtkImporter#3]
Hi! Sorry to bother you with this but I found a bug which is quitte annoying and while I love to fix this myself. I couldn't find the issue. When using "tiles" layers and just placing the whole tilegrid in the map. Collisions are all over the place **when the first tile is solid**.

**Steps to reproduce**
1. Create a new layer or if the PR hasn't been merged yet, just replace the "current auto-layer layer with a tiles layer.
2. Place the complete grid like so:
![Screenshot 2022-06-07 at 08 36 39](https://user-images.githubusercontent.com/3491721/172313202-8f049206-e43f-40c1-b828-290532390cc1.png)
3. Notice collisions are all over the place.
![Screenshot 2022-06-07 at 08 37 48](https://user-images.githubusercontent.com/3491721/172313246-1a846ffe-80b1-4d65-a793-795db4f20f3f.png)

**Weird behaviour**
When removing the "solid" tag from the first tile, lot's of collisions seem to be OK again.

![Screenshot 2022-06-07 at 08 37 21](https://user-images.githubusercontent.com/3491721/172313464-f42e1a98-3a6f-4c98-9754-54767b47054f.png)
![Screenshot 2022-06-07 at 08 37 12](https://user-images.githubusercontent.com/3491721/172313473-6929b6c1-1a25-4f7d-a841-124bd189c9a1.png)

I know this is just an example project for a basic LDtk implementation without any meaning of support. But if you would have a look at it I (and the rest of the Cotton community) would be most thankful.

**Comment by NicMagnier** [comment]
Interesting. I will have a look at this issue. I have an idea what it might be.

**Comment by unbelievableflavour** [comment]
Thanks! Also found another bug which may or may not be related. When using a different tileset, I also get some collision issues.

Here's the tileset.
![TestTiles-table-16-16](https://user-images.githubusercontent.com/3491721/172330984-a0f149e1-2bd5-434c-a2e5-a2d483d56b90.png)

Here's the collision I set for the tileset.
![Screenshot 2022-06-07 at 10 14 23](https://user-images.githubusercontent.com/3491721/172331096-f9d244ff-f17e-4cf8-8fa0-6091ed3de81f.png)

And here is the collision ingame.
![Screenshot 2022-06-07 at 10 15 00](https://user-images.githubusercontent.com/3491721/172331153-52d54894-2a67-482c-af52-754381ac8cdd.png)

**Comment by NicMagnier** [comment]
That might be related to this SDK bug when the tileset has more than 256 different tiles.
https://devforum.play.date/t/emptyids-for-tilemap-get-repeated/6043

**Comment by unbelievableflavour** [comment]
Ah, thanks I was breaking my mind over this problem! Let's hope that's it and that it gets fixed then! Then it's only the first issue that needs to be looked at :)

**Comment by NicMagnier** [comment]
So the first issue is cause also by the SDK.
When you create a new layer, most of the tilemap will be filled with unset tiles. Since in the SDK you tell the collision to set on empty tile, you cannot actually tell it to set an invalid tile as empty. So all unset tiles are actually solid. This is what you see in the first screenshot with collisions.
What I didn't know is that it seems actually that unset tiles collision might depend on the tile 0 in the tileset. This is what you see in the later screenshot after the tile 0 is not Solid anymore.

I've already asked Panic to be able to ask invalid tile to be set as empty.
https://devforum.play.date/t/allowing-getcollisionrects-to-use-invalid-tileid/5465

Right now the fix in LDtk is to set all the tiles properly. But it unearthed another issue I will have to document and file.
What I tried to do is to change a tile to be fully transparent (and not solid) and to fill the tilemap with this.
It does work but it seems a fully transparent tile will be rendered as an opaque white tile. So that screw up all the rendering at the moment (but the collision works)

**Comment by unbelievableflavour** [comment]
So just asking for clarification. Best would be to wait for linked SDK issue to be fixed? Also, some good news, the second issue has been discussed with Dave, and he seem to have made a fix for the next SDK update!
https://devforum.play.date/t/emptyids-for-tilemap-get-repeated/6043

**Comment by unbelievableflavour** [comment]
Fixed in 1.12.0!
